### PR TITLE
Gbl histograms with non-hard coded dut IDs

### PR DESCRIPTION
**Pull request by dvbruch**
So far, residual and pull distributions for DUT planes were only filled for ID numbers 20 and 21. I changed it to be independent of the ID, the requirement for DUT planes is to be larger than 9.

### CODE REVIEW

**Comment by tbisanz** [comment]
@AlexanderMorton can we get an update on this and merge it ASAP - it's very bad habit keeping stuff like this laying around for so long :P

**Comment by AlexanderMorton** [comment]
The only comment I would add before we merge this is that it appears this will only work with DUT ID > 9 ?

@dvbruch If you update this pull request to allow DUT ID> 5 then this should be good to merge to master.

**Comment by dvbruch** [comment]
I changed GBLTrackFit to work with DUT ID > 5, so probably @AlexanderMorton can merge the branch into master?

**Comment by AlexanderMorton** [comment]
@dvbruch , I have taken your PR, fixed the conflicts and added this to the master branch.

**Pull request merged**
