### PR TITLE
TBMon2 compatible output

### PR DESCRIPTION
**Pull request by maweer**
Hello,

I have changed some stuff in the GBLOutput to make the output compatible with TBMon2. Please check, if you are okay with the changes and that they do not disturb the output you are using.

Cheers,
Mareike

### CODE REVIEW

**Comment by TCThenna** [comment]
@edorossi @jha92 
Is shifting the stored local position by half pitch appropriate for you?

**Comment by jha92** [comment]
Hi,
some first comments from my side:
1) shifting by pitch position can influence at least the SUT behavior, as there the pitch is normally arbitrarily. Maybe one has to set it then explicitly to zero in the gear file. For the effect on the Mimosas I am not sure, if it works as expected then (in the case you create a full output).
2) why is the friendship of the tree's needed, so `_euhits` has `_zstree` and `_eutracks` as friends?
3) the added version tree contains only one number, which is 2; is there not a nicer solution for this than writing a tree for it?

**Comment by jha92** [comment]
For 1): Right, I was blindly following Hendrik's remark about the pitch, but it is by sensitive area. I am not really sure about a "convention" how to best dump data in terms of the point of origin of the coordinate system. But anyway, a minor topic.
For 2): Yes, I think so too after looking at https://gitlab.cern.ch/tbmon2/tbmon2/blob/dortmund.dev/preprocess/src/EuBuildTrack.cc#L83 . Have you tried it out without the friendship?
For 3): I see how you use it ( https://gitlab.cern.ch/tbmon2/tbmon2/blob/dortmund.dev/core/src/TBCore.cc#L384 ). But it is very specific for TBmon2 (at least for now). Either one can use it also for other following analysis or we can decide to accommodate your needs by introducing a flag argument.

In general, I think we will not merge your part in the BTTB7 branch but rather then for the foreseen release in the master.

**Comment by edorossi** [comment]
Hi All,

1) I agree with the shift by half sensor size. In EUTelescope the center of the local coordinate system is the geometrical center of the device, which makes sense for the reconstruction. In the analysis, it is preferred to have the center in the edge of the sensor, so you can pass to the pixel coordinate system just by dividing by the pitch sizes. 

2) Does anyone knows what the "friendship" does? I deleted it since I have no clue about it, and if it no necessary I would prefer not to insert it in order to have a code easier to understand. I think that for now we can just accept the change and investigate later, if everyone is fine with this.

3) I don't particularly like the version TTree, but it is true that there is no better way to insert that information. It is not nice, but it is a minor change, so I think we can accept the change and think later if we can improve it.

And @jha92 I agree with you that this should go in the (future) master branch instead of the BTTB7 branch. We should probably speed it up the GBL merge request. I think the only last point left was to have EUTelMille compatible with the updated EUTelPedeGEAR, but the fix will arrive later today. 

Cheers,

Edo

**Comment by edorossi** [comment]
I cherry picked the commit and added to the GBL merge request #447. @TCThenna and @jha92 , is it fine?
(I was trying to actually open a merge request there, but it didn't work out as I wanted)

**Comment by edorossi** [comment]
The commits have been merged in the master together with the merge request #447. I close this merge request since it will be part of the next EUTelescope tag, which I am preparing, while the BTTB7 branch can be considered outdated (and possibly it will be removed).

**Pull request closed without merging**
