### PR TITLE
Following the naming changes in the processors.

### PR DESCRIPTION
**Pull request by mkofarag**
Dear all,

With this commit, I brought up to date our steering templates with the new names for the processors.

Best regards,
Monika

### CODE REVIEW

**Comment by jha92** [comment]
Dear Monika,
to better understand the scope of your ALPIDE analysis as well as separating the currently maintained processors from the ALPIDE ones, could you tell me which processors you need for your analysis. In this case, it makes maybe sense to create a specific folder ALPIDE with these special processors.
Furthermore, is the example already working as expected?
Regards,
Jan-Hendrik

**Comment by mkofarag** [comment]
Dear Jan-Hendrik,

This is a list of all the processors that we are using:
AIDAProcessor
ConditionsProcessor
EUTelAutoPedestalNoiseProcessor
EUTelClusteringProcessor
EUTelCorrelator
EUTelDUTHistograms
EUTelEventNumberPrinter
EUTelHitMaker
EUTelMille
EUTelNativeReader
EUTelNoisyPixelFinder
EUTelOutputSaver
EUTelPreAligner
EUTelProcessorAnalysisPALPIDEfs
EUTelProcessorApplyAlignment
EUTelProcessorClusterAnalysis
EUTelProcessorDeadColumnFinder
EUTelProcessorALPIDEClusterFilter
EUTelProcessorAnalysisPALPIDEfsNoise
EUTelProcessorApplyAlignment
EUTelTestFitter

The example is not yet working as if I see correctly EUTelMille is not available anymore. We are still looking at what should be used instead, but if you have suggestions that would be useful.

Best regards,
Monika

**Comment by mkofarag** [comment]
Dear Jan-Hendrik,

Are there any news on this pull request?

Best regards,
Monika

**Comment by jha92** [comment]
Dear Monika,
sorry for not answering on your reply, was a bit busy with other projects.
Thanks for the list of required processors. EUTelMille was in contrast to our new GBL implementation and therefore we removed it for now, but the functionality should be also available with the new EUTelGBL processor. Moreover, I do not like the EUTelProcessorApplyAlignment processor in your list as this is somehow old style to apply the alignment manually instead of creating new GEAR files for the alignment procedure. For this, we have to look a bit more in detail in the reconstruction chain, for which it would of course be helpful to have an example.
Additionally, I would like to restructure some processors a bit, for example it maybe makes sense to create a subfolder for ALPIDE in the processors folder similar to cms or alibava to host your project specific processors. But that I can do in parallel to your contributions to create a working example.
So after a lot of text, I will merge the PR now to not hinder you in progressing.
Cheers,
J-H

**Comment by mkofarag** [comment]
Dear Jan-Hendrik,

Thank you very much! We'll move to EUTelGBL then and we'll look into removing EUTelProcessorApplyAlignment and using the new way of creating new GEAR files. I think these both should be possible to implement.

Best regards,
Monika

**Comment by jha92** [comment]
Hi Monika,
it was confused and thought we removed EUTelMille, which was not the intention as it used also for alibava example. We only changed one interface setting in the process of introducing EUTelGBL. Maybe there is another problem with EUTelMille, as Mareike is also pointing out a problem there. So we will check in that respect what is happening there.

**Comment by mkofarag** [comment]
Hi Jan-Hendrik,

Thank you very much!

Cheers,
Monika

**Pull request merged**
