### PR TITLE
Added test cases to validate output

### PR DESCRIPTION
**Pull request by tbisanz**

### CODE REVIEW

**Comment by tbisanz** [comment]
I would be very happe if one of you could check this as well: @edorossi? Checkout, and do:

```
cd build
cmake ..
make install (-j X)
ctest -R aconite-4chipLocal_test/*
```

**Comment by edorossi** [comment]
Give me a couple of hours and I will do it!

**Comment by tbisanz** [comment]
Yes, is it possible to get some EUDAQ?

**Comment by edorossi** [comment]
@tbisanz , I have tried one more time to recompile EUDAQ 1.8 but it fails, I am sorry. But @dreyling says that he can try at some point next week!

**Comment by tbisanz** [comment]
Just make a quick clean install on the NAF? With the most recent fixes this should work out of the box (would also be a good validation!)

**Comment by edorossi** [comment]
I will try now! Just as a quick double check: I use dev-desynaf as a ilcinstall branch, and no further modifications to the release version, right?

**Comment by tbisanz** [comment]
Exactly

**Comment by edorossi** [comment]
Just finished. 3 tests are failing and they are all related to tracking:

[ctest.txt.txt](https://github.com/eutelescope/eutelescope/files/2037068/ctest.txt.txt)

Did you change something in the example or I should double check it directly by running jobsub explicitly?

Regarding the installation, it took me a couple of tries. I have used the ATLAS software on NAF. The main steps I did were:

1) clone the dev-desynaf branch of ilcinstall 
2) export the variable ILCSOFT
3) setup gcc 6.2
4) setup cmake 3.10.0 (but probably not necessary)
5) setup git 2.11.1 (default in the ATLAS software)
6) ilcinstall 
7) source init_ilcsoft.sh
8) delete ":$MARLIN_DLL" that was at the end of the command export MARLIN_DLL, in build_env.sh (or only ":$MARLIN", I can't remember)
9) source build_env.sh

In particular, if I don't delete that string :$MARLIN_DLL, when I try to run with jobsub it stops because MARLIN tries to load duplicate libraries. I had to delete it even in the other installation I have for the master branch. However, in general I have always had problems with MARLIN_DLL.

**Comment by tbisanz** [comment]
Can you run each test with verbose output and paste is?

`ctest -V aconite-4chipLocal_test/test_07-6_pede_result.conf` (and same for the other two)

**Comment by edorossi** [comment]
I have copied and pasted your command, and it looks like somehow it ran directly on all the tests :)
I see that a few tests have failed. I attach the log files that have been generated:

[CTestCostData.txt](https://github.com/eutelescope/eutelescope/files/2037484/CTestCostData.txt)
[LastTest.log](https://github.com/eutelescope/eutelescope/files/2037485/LastTest.log)
[LastTestsFailed.log](https://github.com/eutelescope/eutelescope/files/2037486/LastTestsFailed.log)

Unfortunately, I don't have the direct output of the terminal, since my connection crashed at some point after the end of the tests (and I had not been wise enough to run with nohup). Let me know if you need something more!

**Comment by dreyling** [comment]
Tomorrow I could test something, what is the status here or what could I do?

**Comment by tbisanz** [comment]
@dreyling Yes please! Let's move to #400

**Pull request merged**
