### PR TITLE
New features and bug fixes for the pALPIDEfs

### PR DESCRIPTION
**Pull request by mkofarag**
Hi,

We would like to merge our newest changes for the EUTelescope software. We added a few changes related to the pALPIDEfs:
- A bug in the analysis code of the pALPIDEfs was corrected
- Log levels in the example steering templates were adjusted
- An example config file and runlist for the pALPIDEfs was added. Now the config file contains the path pointing to our example data. Would you prefer to move these two files to a DESY server or is distributing them like this fine for you?

There was one change in the EUTelClusteringProcessor.cc code also where a new histogram which stores the time stamps of the events was added and some log output related to this histogram was also added.

Best regards,
Monika

### CODE REVIEW

**Comment by tbisanz** [comment]
Hey, we're usually using histograms via this AIDA interface, this also ensures that they are written out. I'm not entirely happy with the AIDA interface myself, but maybe it's better to stay consistent within one processor. 
To be honest, I'm not sure if you can use it like ROOT histogramms, if this is not possible then we could also leave it like this.

**Comment by mkofarag** [comment]
Hey,
The reason I used a Root histogram is I think there is no corresponding function in the AIDA version for the GetMaximumBin() function in Root. I think tough that it is possible to write the maximum finding algorithm from the existing functions in AIDA, so if you say it's necessary I'll try to rewrite it using only the AIDA interface.

**Comment by mkofarag** [comment]
Hey,
I pushed a new version where I replaced the Root histogram by the AIDA version.

**Comment by tbisanz** [comment]
Thanks!

**Comment by mkofarag** [comment]
Thanks for the quick merge!

**Pull request merged**
