### PR TITLE
Bugsandcosmetics

### PR DESCRIPTION
**Pull request by gollumben**
Several changes to the code were applied.

**EUTelTestFitter.cc**
1.) The EUTelTestFitter.cc was modified such that the alignment shifts and rotations are consistent with the EUTelProcessorApplyAlignment.cc. Also, the order the rotations from the gearFile are applied was made consistent with other files from the EUTelescope-framework, e.g. the HitMaker, the Alignment (EUTelMille.cc) and the EUTelProcessorApplyAlignment.cc. This rotation order chosen was first around the global X-axis, then around the global Y-axis and finally around the global Z-axis. 

Additionally, the function getFastTrackImpactPoint was replaced by a function called getImpactPoint. Both functions do the same thing, which is calculating the correct coordinates of the impact point. This is required, since the TestFitter extrapolates the track to a perpendicular plane (i.e. the normal vector is directed in z-direction) centred at the centre of the plane of interest. However, it might be that this plane is rotated and the getFastTrackImpactPoint and getImpactPoint take care of that. The new function getImpactPoint has two advantages. First, it allows for an easy usage of a track slope. So far, the track direction is set to be in z-direction (i.e. zero slope), but in principle one could add the slope of a track here. Secondly, the new function does not require matrix inversion, which makes it more efficient.

**EUTelGeometryTelscopeGeoDescription.cpp**
2.) In order to make the rotation-order consistent, the EUTelGeometryTelscopeGeoDescription.cpp was changed in order to have the rotation-order: first around the global X-axis, then around the global Y-axis and finally around the global Z-axis. Since this also goes into the HitMaker, all rotations in the HitMaker now have the order X,Y,Z. After this change, the rotation order of the HitMaker, the EUTelGeometryTelscopeGeoDescription, the Alignment (EUTelMille.cc), the EUTelProcessorApplyAlignment.cc and the EUTelTestFitter.cc are the same. If this change should be rejected, the rotation order in all mentioned files should be checked for consistency. Additionally, the rotation order in our next pull request, from the branch analysisupdate, also has to be changed correspondingly. I also suggest to document somewhere, which rotation-order is used. On long-term basis one could also consider making the rotation order a parameter, for example from the config-file. 

**EUTelMille.cc**
3.) The binsize and the plot ranges of the histograms drawn by EUTelMille.cc were increased, since reading the resulting histograms otherwise was difficult for our data.

**steering-template files**
4.) Some purely cosmetic changes were applied to some steering-template files.

**Old pull request**
5.) I hope you have not forgotten about our old pull request about the EUTelProcessorClusterAnalysis.cc :wink: .

Please come back to me, if you have any questions.

### CODE REVIEW

**Comment by tbisanz** [comment]
I merged your old PRs - this one however, I have to look into a bit further. I have to ensure that no other parts of the framework rely on the ordering of these angles. Also - this will break old GEAR files from users and thus has to be carefully checked. I however agree, that we need a consistent and better documented ordering of the angles.

**Comment by tbisanz** [comment]
Let me just write a quick follow up, I'm at a conference right now and won't be able to look into this in more depth this week.

In the next few weeks I plan on removing the external alignment collection completely. The idea is, that the GEAR file contains all the alignment constants and gets updated accordingly. Check out the aconite-4chipLocal example to see how it works. Of course, we still need a consistent and correct order of rotations - so this obviously doesn't resolve this issue. Maybe you could try out this way of using the alignment and check if it works with your processors and obviously gives the same results.

**Comment by tbisanz** [comment]
So, I've looked into this, in most places we use Tait-Bryan Angles in the convention: YXZ, i.e. initial Z rotation, followed by X and ultimately Y. This is what we should stick to and keep.

**Comment by gollumben** [comment]
Dear Tobias,

in how many places is this convention actually used?

**Comment by tbisanz** [comment]
Hey,

In the backend of the GEAR format, i.e. EUTelGeometryDescription and the EUTelMille alignment processor. It is incorrectly used in the ApplyAlignment processor(s) - but these are to be removed anyways in the master branch in the future, see #210. So the two choices we have are either change them in the already existing and working implementation to make them work with the outdated alignment databases, or keep them as they are and remove the alignment databases to force processors to not use them anymore (which will happen anyways).

The problem in changing the implementation, is that it will break old GEAR files which stick to the current implementation.

**Pull request closed without merging**
