### PR TITLE
Initial integration of ALICE ITS Upgrade Code for the pALPIDE-1 prototype

### PR DESCRIPTION
**Pull request by mkofarag**
Hello,

we would like to contribute code which we developed within the ALICE ITS Upgrade project. This code is used for the analysis of pALPIDE-1 data.

Furthermore, we did the following changes to common classes:
- Using the time value of clusters, hits and so on to identify a cluster. This value was unused, but existing in LCIO.
- EUTelClusteringProcesser: Added a protection against too large clusters letting the underlying data structures overflow and crash

Regards,
Felix and Monika

### CODE REVIEW

**Comment by tbisanz** [comment]
Hey, thanks a lot - I'll try to look through your code and changes ASAP. I see that you included an example (jobsub/examples/pALPIDEfs). 
Is it possible to make a small portion of data involved publically available? Just enough so that people who do a similar analysis can use yours as a starting point and actually try out running your example.

**Comment by mkofarag** [comment]
Hey,
Thanks for the quick reply! I think making some of our data available is a good idea, but we need to discuss it within our group first!

**Comment by mkofarag** [comment]
Hey,
Did you have the opportunity to start looking into our changes? I discussed with my colleagues and it is no problem to provide some example data to try our examples.
Cheers, Monika

**Comment by tbisanz** [comment]
Yes, sorry for the delay - I have two issues which prevent me from merging. Please don"t include any using namespace XYZ in any header file - every file which includes this will be polluted with those. Aside from that, could you quickly describe the changes in src/EUTelClusteringProcessor.cc?

**Comment by tbisanz** [comment]
Ok - I quickly looked through your changes, they are mostly indentation. For the issue with the 32 bit overflow - I'm not happy with the implementation of that in EUTelescope in general, we should come up with a better solution for that, but it is fine for now I guess. Please fix the namespace thing and we'll merge! :-)

**Comment by mkofarag** [comment]
Hey,
Sorry for the slow reply, I found a few bugs and I thought it's better to solve them before pushing the other changes! I pushed three new commits now:
1. Removed the using namespace XYZ lines from the header files
2. I realized that the cut on the cluster size limit was needed for a part of the code which had been already removed by you and reintroduced by us. Since we don't actually need it, I removed it again. Now it does not crash and also does not require the limit on the size. Now the only changes in src/EUTelClusteringProcessor.cc which are not indentation are the ones for setting the time value of the clusters to be used as ID.
3. I found a few bug in our src/AnalysisPALPIDEfs.cc and corrected it.
Please tell me if there's anything else needed to be done for the merging!

**Comment by tbisanz** [comment]
Looks fine to me, thanks!

**Comment by freidt** [comment]
Thanks a lot @tbisanz on behalf of the ALICE ITS Upgrade team!

**Comment by tbisanz** [comment]
@mkofarag @freidt Maybe just a small remark on this PR: We use a naming scheme with EUTelProcessor* for everything which is a Marlin processor (i.e. inherits from the Marlin Processor base class). Also we don't interface GEAR directly anymore - instead we use  eutelescope/include/EUTelGeometryTelescopeGeoDescription.h which is available as a global instance via geo::gGeometry(). In particular, https://github.com/eutelescope/eutelescope/blob/master/include/EUTelGeometryTelescopeGeoDescription.h#L306 will return you a vector of all sensor IDs ordered according to their z-Position. Using the sensor IDs you can get all the information from the GEAR file. We will soon make big changes to GEAR and if you want this processor to keep functioning properly, it might be a good idea to update this some time in the future. If you have any questions, feel free to ask!

**Comment by mkofarag** [comment]
Thank you @tbisanz for this notification! We would like to continue using this processor, so we'll make the necessary changes and do a new pull request once it's done.

**Pull request merged**
