### PR TITLE
Mainly compiler warning fixes

### PR DESCRIPTION
**Pull request by tbisanz**

### CODE REVIEW

**Comment by tbisanz** [comment]
Once this is through CI, I'll merge this. @edorossi @TCThenna

**Comment by tbisanz** [comment]
No warnings on all tested compilers! aconite-4ChipLocal provides same results!

**Comment by jha92** [comment]
@tbisanz 
I recently pulled the newest EUTel version and wanted to recompile. 
My previous setup/installation was still based on eudaq-dev1.7 but before it was not working anymore and the master was something around 80 commits behind.
When recompiling the newer version, it breaks due to errors, which were before warnings. I guess it is connected to your commit "Warnings are now treated as errors, lets hope this works". Recompiling the old master works fine.
Not sure if it is really an issue, but would like to know the reason: ideas?
 @dreyling said to me, with his fresh installation he runs not in this behaviour, therefore I am currently doing the same.

**Comment by tbisanz** [comment]
@jha92 If a clean install breaks, please open a new issue! If modifications with your code break, fix the errors and it should compile!

**Comment by tbisanz** [comment]
Furthermore, don't comment too much in merged/closed issues/PRs as they won't show up on top, but open a new issue and refer to them ;) I nearly missed this post!

**Comment by jha92** [comment]
Okay, sorry, I will do so in the future (thanks for the example). Thought notifiying you with @tbisanz would work enough :)

**Pull request merged**
