### PR TITLE
 Removing g++ compilation errors

### PR DESCRIPTION
**Pull request by dfigueiredo**
const const changed to const and commenting not used variables.

### CODE REVIEW

**Comment by edorossi** [comment]
Hi @dfigueiredo , I am just waiting for the build jobs and then I will merge!

**Comment by dfigueiredo** [comment]
Ciao Edo, 

Perfect. Included you only for sanity checks! ;)

Best,
Diego.

**Comment by jha92** [comment]
Hi Diego,
just for my understanding:
1) where did the g++ compilation error showed up?
2) unfortunately, it is hard to track now the real changes, as you (or your editor) changed completely the code style...

**Comment by TCThenna** [comment]
@edorossi Edo, could you revert the merge? And @dfigueiredo please change the pull request such that the original style is maintained. Independent of the fact, if the old style is nice/beautiful/... or not, it should remain consistent with the rest. 

thanks,
Hendrik

**Comment by jha92** [comment]
Hi Hendrik,
yes, I am just thinking the same about reverting it in this version.

**Comment by jha92** [comment]
So, I reverted for now. But we are happy to receive a new PR from you, @dfigueiredo :)
Cheers,
Jan-Hendrik

**Comment by dfigueiredo** [comment]
Hi guys,

Indeed, sorry for this indentation. My bad. I used to do it "automatically" every time I save a code. ;)
Finally, I have used gcc (GCC) 6.2.0 to compile this code. 

If you would like, I can later redo the changes keeping the indentation.

Have a great time,
Diego.

**Pull request merged**
