### PR TITLE
ALPIDE bringing up to date our code

### PR DESCRIPTION
**Pull request by mkofarag**
Dear Developers,

As you know the code used for the test beam and analysis of the ALPIDE chip was not updated for a while because of problems in our conventions of the rotations. This pull request tries to bring up to date our code with the current version in the repository. All commits except the last one touch only our analysis code and our example files. The last commit, however, changes the order of rotations in EUTelGeometryTelescopeGeoDescription, which is a central part of the code. In this file the rotation order is now ZXY which we propose to change to XYZ as this is the order used in the EUTelTestFitter and the EUTelProcessorApplyAlignment processors. We are not using Z rotations normally, so for us this change is not essential; however, if it is kept as it is now, it is not consistent with EUTelTestFitter (with the lines around 886). So then this processor has to be adjusted. Let me know whether this change is acceptable for you.

Best regards,
Monika

### CODE REVIEW

**Comment by mkofarag** [comment]
@freidt

**Comment by mkofarag** [comment]
@TCThenna @tbisanz @freidt 

No, not yet. The idea was that with this pull request we reproduce the same stage of our analysis as the one where we diverged (e.g. the same processors are used where possible). We want to go through all the new processors and functionalities that were introduced since then soon, but I would prefer to keep that separately, so that we don't diverge any further until that is done.

**Comment by mkofarag** [comment]
@TCThenna @tbisanz @freidt 

Do you already see when you will have time to look into this pull request?

Thank you, Monika

**Comment by tbisanz** [comment]
Hey, I can merge this if you take out the rotation changes - they are inconsistent with other parts, e.g. the alignment in the GEAR file, the DAF fitter etc.

EUTelTestFitter should be either removed or updated to stick to the rotations!

**Comment by mkofarag** [comment]
Hi @tbisanz,

With the last commit I removed the change of the rotations and adjusted EUTelTestFitter and our analysis to this version of the rotations. Would this version be acceptable for you?

**Pull request merged**
