### PR TITLE
Updated GBL processor

### PR DESCRIPTION
**Pull request by edorossi**

### CODE REVIEW

**Comment by thomaseichhorn** [comment]
I installed this branch and tested its usability with alibava and CMS OT DUT data. So far, I found the following issues in the GBL alignment:
- chi2 cut doesn't work (it is a probability cut in the code, which is something else)
- residual vs. track x position and vs. track y position plots are really needed to see rotational misalignment
- can the histogram ranges be adjusted according to pitch sizes? Especially needed for strips / long pixels...
- maxTrackCandidates parameter has no use, only maxTrackCandidatesTotal. The first should be a limit on the good tracks passing all cuts, the latter on the tracks found from combinatorics...
- if performAlignment is false, there is no output of the number of tracks found during running
- in alignMode XYShiftsRotZ, sometimes EUTelPedeGEAR gives the following error:

(INFO): [ MESSAGE4 "MyEUTelPedeGEAR"]
(INFO): [ MESSAGE4 "MyEUTelPedeGEAR"]  Read all binary data files:
(INFO): [ MESSAGE4 "MyEUTelPedeGEAR"] readC: problem with stream or EOF reading ints
(INFO): [ MESSAGE4 "MyEUTelPedeGEAR"]  Read error for binary Cfile           1 record       13882 :         -16
(ERROR): [ ERROR5 "MyEUTelPedeGEAR"] STOP PEREAD: stopping due to read errors
(ERROR): [ ERROR5 "MyEUTelPedeGEAR"] Problem during Pede execution, exit status: 0, error messages (repeated here):
(ERROR): [ ERROR5 "MyEUTelPedeGEAR"] STOP PEREAD: stopping due to read errors
(ERROR): [ ERROR5 "MyEUTelPedeGEAR"]
(ERROR): [ ERROR5 "MyEUTelPedeGEAR"] Will exit now

The error doesn't occur however, if XYZShiftsRotXYZ is selected...

**Comment by TCThenna** [comment]
Thomas also mentioned, that the order of application of Euler angles should be checked with the one used in MillepedeII. @edorossi Which order is used at the moment ?

**Comment by edorossi** [comment]
Some of @thomaseichhorn points have been solved and I am working on the others. Here a brief recap:

>     * chi2 cut doesn't work (it is a probability cut in the code, which is something else)

Fixed. Now the cut is effectively a chi2 cut (actually the cut is on chi2 / Ndf, but it is explained in the parameter description)

>     * residual vs. track x position and vs. track y position plots are really needed to see rotational misalignment

I am working on it and I will implement it very soon. The main problem is to decide the best format for the plots (I am also considering a possible 2D plot).

>     * can the histogram ranges be adjusted according to pitch sizes? Especially needed for strips / long pixels...

Since the plots are in global coordinate system, this can't be done easily now. The problem is similar to what described in #443 : if a device is rotated by 90 degrees, the plot in the x (y) direction corresponds to the y (x) direction of the device. Thus readjusting the plots by the pitch can create quite a few problems.
I will postpone this feature to a moment where we will have everything in local coordinates.

>     * maxTrackCandidates parameter has no use, only maxTrackCandidatesTotal. The first should be a limit on the good tracks passing all cuts, the latter on the tracks found from combinatorics...

Only the cut on the total number of track candidates has been left for now, the other has been removed. Since it is not urgent I would leave for later the discussion on having a cut on the combinatorial number of tracks.

>     * if performAlignment is false, there is no output of the number of tracks found during running

Working on it, I will fix it very soon.

>     * in alignMode XYShiftsRotZ, sometimes EUTelPedeGEAR gives the following error:
> 
> The error doesn't occur however, if XYZShiftsRotXYZ is selected...

I am trying to replicate the error, but to me it runs fine. I think there are two possible causes:

- EUTelPedeGEAR should be executed before EUTelGBL in the steering files. This would depend on your setup, but if they are swapped, it could explain the problem you are seeing.

- a recent refactoring of the Millepede steering file generation. I am looking into it!

> Thomas also mentioned, that the order of application of Euler angles should be checked against the one used in MillepedeII. @edorossi Which order is used at the moment in eutel?

Regarding this, I most probably need some help. For the rotation, we are mostly using functions I have never deeply investigated. However, if I understand correctly, Millepede is using the rotations around the three cartesian coordinates. I can check that the order we use is the same used in Millepede (how can I check the latter though?).
I am a bit clueless about this though. Is there something else I am missing?

**Comment by TCThenna** [comment]
> Fixed. Now the cut is effectively a chi2 cut (actually the cut is on chi2 / Ndf, but it is explained in the parameter description)

What is the benefit of cutting on chi2 or chi2/ndf im comparison to probchi2?

**Comment by TCThenna** [comment]
> I am working on it and I will implement it very soon. The main problem is to decide the best format for the plots (I am also considering a possible 2D plot).

I would propose a TProfile, filling the abs(res)

**Comment by TCThenna** [comment]
I think Thomas knows the order

**Comment by thomaseichhorn** [comment]
EUTelProcessorApplyAlignment (and more important, mllepede) have the following correct* order of applying alignment:

1) rotate plane centre around global x by - alpha
2) rotate plane centre around global y by - beta
3) rotate plane centre around global z by - gamma
4) subtract x alignment from plane centre 
5) subtract y alignment from plane centre 
6) subtract z alignment from plane centre 


The Gear/EuTelGeo variant uses a rotation matrix (in eutelescope/libraries/src/EUTelUtility.cc) with the application order (according to comment):

"YXZ, i.e. initial Z-rotation, followed by X and ultimately Y rotation."

Assuming these are rotations around the global axes (and not local axes!), the order has to be changed by using a different rotation matrix...


* = At the end of the day, one has to choose one rotation order around one set of axes. This order has to be the same in millepede and EUTelescope...

**Comment by edorossi** [comment]
> We have to keep in mind here, that the unique function interacts with the vector used then in the loop. Therefore, it is not really unused.

I see the point, but the compiler considers it as unused. The standard compiler is treating it as an error and thus stopping the compilation.

**Comment by TCThenna** [comment]
> EUTelProcessorApplyAlignment (and more important, mllepede) have the following correct* order of applying alignment:
> 
>     1. rotate plane centre around global x by - alpha
> 
>     2. rotate plane centre around global y by - beta
> 
>     3. rotate plane centre around global z by - gamma
> 
>     4. subtract x alignment from plane centre
> 
>     5. subtract y alignment from plane centre
> 
>     6. subtract z alignment from plane centre
> 
> 
> The Gear/EuTelGeo variant uses a rotation matrix (in eutelescope/libraries/src/EUTelUtility.cc) with the application order (according to comment):
> 
> "YXZ, i.e. initial Z-rotation, followed by X and ultimately Y rotation."
> 
> Assuming these are rotations around the global axes (and not local axes!), the order has to be changed by using a different rotation matrix...
> 
>     * = At the end of the day, one has to choose one rotation order around one set of axes. This order has to be the same in millepede and EUTelescope...

I talked with Claus:
In principle, rotations are neither linear nor do they commutate, but as we assume the small angle approximation to be valid, they are linear (cos(x) -> 1, sin(x) = x). They might still not commutate, but this only means you take different paths from your starting point ( alpha = beta = gamma = 0) to your minimum depending on your chosen order of application. The method itself should still convergence against the same set of alignment constants.

**Comment by edorossi** [comment]
Hi @TCThenna @thomaseichhorn ,
Using the Millepede convention, we should apply the rotations in XYZ order in EUTelUtility, right? (I am sorry for the stupid question, but I get very confused with rotations :) ).
The assumption of small angles is not true for rotations of 90 degrees, which are fairly common. I have a dataset with such rotation, and I have problems with the alignment of the rotation in XY, and I think it is due to this issue.
As an additional point, the same function is used for DAF as well. Is it right to apply the correction to that case as well?

Cheers,

Edo

**Comment by TCThenna** [comment]
> we should apply the rotations in XYZ order in EUTelUtility, right?
There is no convention of order in MP, if I understood correctly. It just solves linear equations, with many parameters. Have a read here, if you fancy:
http://www.desy.de/~kleinwrt/MP2/doc/html/draftman_page.html#sssec-mille2

if you only allow for rot around Z, there is two global derivatives added in the matrix, e.g. here
https://github.com/eutelescope/eutelescope/blob/dd3a0e7ae91539570d0fcd4c0bc8b9dc1dcf7779/processors/src/EUTelAlignGBL.cc#L499

if you have more, you just have additional global derivatives, but they are calculated in Pede simultaneously, during the same solving if the system of linear equations. Hence, there is no ordering in Pede

> The assumption of small angles is not true for rotations of 90 degrees
I was talking angles in alignment constants, not your local to global transformations. Pede doesnt care about your local coordinate system, you just have to feed it with the correct data. Pede is also not the one converting from local to global. As long as you provide correct residuals (i.e. distance b/w seed abd measurement, no track fit involved here!), uncertainties, measurements, global and local derivatives, MillePede will do the job. So it is likely, that you somehow provide the data incorrectly, or that we use the corrections provided MP in a wrong way.

> As an additional point, the same function is used for DAF as well. Is it right to apply the correction to that case as well?
which function? the fit function is not important for MP, is just takes residuals to the seed, uncertainties, measurements, global and local derivatives. The way we construct the global derivatives shows that we use straight line approximation for this. I would guess it is the same in the DAF processor.

**Comment by edorossi** [comment]
Hi @TCThenna ,

I am pretty sure that we are using MillePede in the right way (providing the right residuals and such). The problem is that MillePede output gives rotations as angles, where some order convention is implicit (probably XYZ). Then, we are applying a different order convention when we correct the GEAR file (YXZ).
It is basically a problem with how we apply Millepede corrections after its execution, while apart from that we are using it correctly.

This is why a 90 degrees rotation is significant:

> which function?

The function in EUTelUtility.cc which takes angles as an input, and gives the correspondent matrix. This is used by EUTelPedeGear which is used by DAF as well. However, the convention should be the same I guess.

Just in case, to recap the workflow on how the new GEAR angles are calculated:

- The rotation matrix of the old GEAR is calculated from the old angles

- Using the correction angles given by MillePede, a "correction" rotation matrix is calculated (note, the angles are in XYZ convention, while the matrix is calculated assuming YXZ convention!)

- These two matrices are multiplied, in order to obtain the final aligned rotation matrix

- Using the final matrix, we retrieve the final rotation angles to be used in the new GEAR

Right now, we are doing this with functions written "by-hand". The smartest thing would surely be to use some Eigen functions, as done with the old alignment LCIO (for which the last step wasn't needed though). This would require some work, though...

Cheers,

Edo

**Comment by TCThenna** [comment]
I learned today they that there is no implicit order of angles in MP.

Again, the alignment constants are calculated in Pede simultaneously, during the same solving of the system of linear equations. Hence, there is no ordering in Pede

**Comment by edorossi** [comment]
I think the example should be runnable wherever they are, without any modification and in the most intuitive way. At least, I think this is the aim of the example.
For example, I tried to run anemone-2FEI4 and I got stuck because of the wrong path and it took me a few minutes to find out the problem (the error message is not particularly helpful). For a new user it would take much more, so I prefer to change the path and make everything work "out of the box".

**Comment by edorossi** [comment]
@jha92 @TCThenna @dreyling , there are still a few open questions, but this merge request should be merged at some point :)
Is there any important question or problem to be fixed before doing so?

**Comment by thomaseichhorn** [comment]
I ran some simple tests with the latest commits and as far as I can see, the problem remains. As soon as a sensor plane has a non-zero initial gear rotation (or a non-zero rotational correction), EUTelPedeGear (via EUTelUtility) performs some wrong calculations:

Alignment on sensor 6 determined to be:
xOff: 0.0078035 +- 0.00027231
yOff: -0.00095023 +- 0.00027625
zOff: 0 +- 0
alpha: -0.0073905 +- 0.0038532
beta: 0.3267 +- 0.002978
gamma: 8.6182e-05 +- 7.5656e-05
Updated rotations (alpha', beta', gamma'): -0.00739088, 0.344154, -4.28155e-05
**Aligning sensor: 6 to position: 144.217
3.12671
 426.25**
Aligning sensor: 6 to rotation:     0.941361  -0.00245336     0.337391
-4.28143e-05     0.999973   0.00739081
     -0.3374  -0.00697187     0.941336

(small xy and angular corrections lead to a shift in x of ~144mm from the x ~= 0 position)

Whilst the small-angle approximation and thus the order-independence might be true from the pede side, this still has to be implemented properly in EUTelPedeGear... I would then also assume that the angles coming from pede are for rotations around the global axes. The current implementation might rotate first around one global axis, then around a new local axis (c.f. https://en.wikipedia.org/wiki/Euler_angles).

If you want to check this quickly, I uploaded 2 simulated runs with 7 mimosa sensors each. In run 29, the central DUT sensor is rotated by +10 degrees in beta (=xz). Run 30 is the same with no rotated planes... simply run clustering, hitmaker and then gbl...

[test.tar.gz](https://github.com/eutelescope/eutelescope/files/2800212/test.tar.gz)

**Comment by edorossi** [comment]
Hi @thomaseichhorn ,

Thanks for providing the simulated runs. With my runs (where there is no large rotation), I can't replicate the problem. I prepared a fix for the rotation order, which involves Eigen instead of the current explicit declaration of the rotation matrix. I was reluctant to push it, since with my runs I see no difference, but I will test it using your runs to understand what is going on.

It will take a couple of days, but I will let you know if I can find the solution for this problem.

Cheers,

Edo

**Comment by edorossi** [comment]
Hi @thomaseichhorn ,

Perhaps I found the problem, and actually it makes a lot of sense. EUTelPedeGEAR has a flag called RotateOffsetVec. I set it as a standard to be true, can you try to align while it is set to false? 
I tried it, and it looks like it fixes the problem. While investigating it, I realized it is done something totally different from what I thought. Basically, it is rotating the initial XYZ offset with the rotation matrix from the alignment. So if you have a significant correction in ZY or ZX, part of the initial Z position will be inserted in the X and Y shift. That's totally absurd I and I will definitely remove that flag.

However, without that flag activated, I can't align my strip data. So there is something else I am missing...

Cheers,

Edo

**Comment by jha92** [comment]
Hi @edorossi,
maybe you can try to figure out and solve the problem @thomaseichhorn  has found. In the meanwhile, I am also in some modifications for DAF. So let's see, when we reach a clear point for merging. In my point of view, there is not a real rush. It is more important to have everything in a good shape for the users to not break there reconstructions.

**Comment by TCThenna** [comment]
> Perhaps I found the problem, and actually it makes a lot of sense. EUTelPedeGEAR has a flag called RotateOffsetVec. I set it as a standard to be true, can you try to align while it is set to false?
> I tried it, and it looks like it fixes the problem. While investigating it, I realized it is doing something totally different from what I thought. Basically, it is rotating the initial XYZ offset with the rotation matrix from the alignment. So if you have a significant correction in ZY or ZX, part of the initial Z position will be inserted in the X and Y shift. That's totally absurd I and I will definitely remove that flag.
> 
> However, without that flag activated, I can't align my strip data. So there is something else I am missing...

Let's meet this week so you @edorossi can talk us through your findings! Thanks a lot for investigating on this.

**Comment by edorossi** [comment]
Ok, I did some investigating, and I am more confused than before. I removed the flag RotateOffsetVec from EUTelPedeGEAR, since I am very confident it is doing something very wrong (note that originally it was false as default). Now, I can't align my strip data, though, and it looks like the problem is very deep. After some iterations, the residuals center gets at -5um from the center, and it doesn't move from there. In the meanwhile, every iteration step adds a rotation of 0.004 (about 0.2 degrees), and it is not converging.
I already had a weird feeling on that alignment, and I think the flag RotateOffsetVec helped just by chance. 
I tried several things (that should be retested):

- Move the center of the local coordinate system to the center of the beam (to minimize the lever arm)

- Changed the order in which the rotations are applied, using Eigen

- Rotate the alignment shifts by the alignment rotation

And still no improvement... To tell the truth, I am very clueless right now and I don't know what to check next. @TCThenna , @thomaseichhorn , do you have any idea? 

As an additional note, GeometricClustering generates some totally wrong results starting from the prealigner, but before that everything looks fine, even the correlations. I don't really understand how it is possible...

**Comment by edorossi** [comment]
After digging deeper, I have some information about the problem with the rotations. Still, I have not the final solution, but I feel I am pretty close. Here there is a brief recap:

1) The flag rotateOffsetVec was doing it right by performing:
`oldOffset = rotAlign*oldOffset;`
I did some math and it looks reasonable (and without that I can't align my strips).

2) The problem that Thomas was seeing was mainly due to the fact that the code is based on the alignment constants, where the rotation was basically around the center of the device. Now, the rotation is performed around the center in x and y, while z is the z position of the device. So we are basically passing the wrong global derivatives when we set:
`alDer6(0,4) = deltaz; //dx/db`
`alDer6(1,3) = -deltaz; //dy/da`
with deltaz very small. We should replace deltaz with the z position, but here there is the catch: we have a huge lever arm and this creates problems. I didn't try to align Thomas' data again, but I guess that if the initial alpha or beta set in gear are even slightly different from the real ones, this can create huge problems.

3) I still have problems with my strips. I can align them, but the resolution looks awful. Old story short: the gamma rotation is somehow flawed, since by fixing that, everything works fine. It may be due to the fact that X and Y are inverted, so phi->-phi and so, when we set the global derivatives, there is a wrong sign:
`alDer6(0,5) = -ys; //dx/dg`
`alDer6(1,5)` = xs; //dy/dg`
But I tried to fix this by hand and it didn't help. Other reasons may be the fact that we are using inconsistent rotation centers or the rotation order. Need a bit more investigation for this.

**Comment by edorossi** [comment]
By using local coordinates now I can align my strips very well, and the code looks quite reasonable (even though I should clean it a bit).

I can also align @thomaseichhorn tilted simulation. The trick was in the global derivatives matrix: 

`alDer6(0,4) = z; //dx/db`
`alDer6(1,3) = -z; //dy/da`

If I set an initial rotation between 5 and 15 degrees, the ZX rotation converges to the real value of 10 (within 0.02 degrees) in three iterations. Only some minor tweaks to the resolution are involved. This is rather surprising given the huge lever arm and the consequent large x and y shifts involved. 

Now the problem is that if there is an initial ZX or ZY rotation of 0, then the global derivatives matrix is flawed (rank defect) if you don't fix such rotations. I am investigating it and it should be relatively quick to fix.

**Comment by TCThenna** [comment]
> By using local coordinates now I can align my strips very well, and the code looks quite reasonable (even though I should clean it a bit).

I am pretty sure Claus is using the proL2M Matrix, and not proM2L when adding measurements. Are you sure that when using the corrected global derivatives, you still need the local coordinates?

**Comment by edorossi** [comment]
> I am pretty sure Claus is using the proL2M Matrix, and not proM2L when adding measurements. Are you sure that when using the corrected global derivatives, you still need the local coordinates?

However, I think the main problem is nomenclature. Claus defines the local coordinate system as the system that follows the track. In our case we don't follow the track, so we use the global coordinate system for this purpose (that is also why the code looks a bit different). Then, Claus defines measurement coordinate system what we call local coordinate system. So, we use the matrix proM2l (master to local) which correspond to Claus' proL2m (local to measurement). 
In any case, the code for local coordinate system is still preliminary and I want to have a chat with Claus before putting this out, just to be sure that the code is not doing something totally wrong.

**Comment by TCThenna** [comment]
I am not at DESY this week, but let me know in case you meet Claus next week, so I can join!
We can also talk with Claus about using 

> alDer6(0,4) = z; //dx/db
> alDer6(1,3) = -z; //dy/da

instead of dz, and how to deal with the rank defects, because many start with zero rotations (although not everyone will align in XZ and YZ.

**Pull request merged**
